name: Send email notification
on:
  push: 
jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        if: ${{ always() }}
        uses: devellany/send-mailer@v3
        with:
                host: smtp.google.com
                serverPort: 465
                account: ${{secrets.MAIL_ADDRESS}}
                password: ${{secrets.MAIL_PASSWORD}}
                sender: devellany
                from: ${{secrets.MAIL_ADDRESS}}
                to: mohammedsalik2511@gmail.com
                subject: mail title.
                body: file://README.md
                contentType: text/html
                attachments: file://attachments.json