name: Send email notification
on:
  push: 
jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Deployment Email
        uses: wesdevteam/maileraction@v1
        with:
          to: team@example.com
          subject: "âœ… Production Deployment Complete"
          text: "The deployment was completed successfully."
          html: "<p>The <strong>deployment</strong> to production was successful ðŸŽ‰</p>"
        env:
          MAIL: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_HOST: smtp.gmail.com
          MAIL_PORT: 465