name: Send email notification

on:
  push:

jobs:
  email-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Deployment Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_ADDRESS }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "âœ… Production Deployment Complete"
          to: team@example.com
          from: ${{ secrets.MAIL_ADDRESS }}
          content_type: text/html
          body: "<p>The <strong>deployment</strong> to production was successful ðŸŽ‰</p>"
          
